import makeWASocket,{DisconnectReason,fetchLatestWaWebVersion,useMultiFileAuthState}from"@whiskeysockets/baileys";import P from"pino";import QRCode from"qrcode";import http from"node:http";import fs from"node:fs";
const apiKey=process.env.WORKER_API_KEY||"",log=P({level:"warn"}),port=Number(process.env.PORT||3000),dataDir=process.env.DATA_DIR||"/data";fs.mkdirSync(dataDir,{recursive:true});
const eventsFile=dataDir+"/events.json",accountsFile=dataDir+"/accounts.json";let events=read(eventsFile,[]);let accounts=read(accountsFile,[{id:"main",name:"Ana WhatsApp",authDir:process.env.AUTH_DIR||"/data/auth",monitored:read(dataDir+"/monitored.json",[])}]);const live=new Map();
function read(f,d){try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return d}}function save(f,d){fs.writeFileSync(f,JSON.stringify(d,null,2))}function persist(){save(accountsFile,accounts.map(a=>({id:a.id,name:a.name,authDir:a.authDir,monitored:a.monitored||[]})))}const json=(r,s,d)=>{r.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"});r.end(JSON.stringify(d))};const body=async req=>{let b="";for await(const c of req)b+=c;return JSON.parse(b||"{}")};const acc=id=>accounts.find(a=>a.id===id);
http.createServer(async(req,res)=>{const u=new URL(req.url||"/","http://localhost"),p=u.pathname,id=u.searchParams.get("accountId")||"main",a=acc(id),l=live.get(id);if(req.method==="OPTIONS"){res.writeHead(204,{"access-control-allow-origin":"*","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,x-api-key"});return res.end()}if(p!=="/health"&&(!apiKey||req.headers["x-api-key"]!==apiKey))return json(res,401,{ok:false,error:"Yetkisiz"});
if(p==="/health")return json(res,200,{ok:true,connected:[...live.values()].some(x=>x.connected),accounts:accounts.map(x=>({id:x.id,name:x.name,connected:!!live.get(x.id)?.connected,qrAvailable:!!live.get(x.id)?.qr,monitoredGroups:(x.monitored||[]).length})),eventCount:events.length});
if(p==="/accounts"&&req.method==="GET")return json(res,200,{ok:true,accounts:accounts.map(x=>({id:x.id,name:x.name,connected:!!live.get(x.id)?.connected,qrAvailable:!!live.get(x.id)?.qr,monitoredGroups:(x.monitored||[]).length}))});
if(p==="/accounts"&&req.method==="POST"){const d=await body(req);const name=String(d.name||"Yeni WhatsApp").trim().slice(0,60),nid="wa-"+Date.now();accounts.push({id:nid,name,authDir:dataDir+"/auth-"+nid,monitored:[]});persist();startAccount(acc(nid));return json(res,200,{ok:true,id:nid,name})}
if(!a)return json(res,404,{ok:false,error:"Hesap bulunamadi"});
if(p==="/events")return json(res,200,{ok:true,events:events.filter(e=>!u.searchParams.get("accountId")||e.accountId===id).slice(0,500)});
if(p==="/groups"){if(!l?.connected)return json(res,503,{ok:false,error:"WhatsApp bagli degil"});if(req.method==="GET"){try{const all=await l.sock.groupFetchAllParticipating();const groups=Object.values(all).map(g=>({id:g.id,name:g.subject||g.id,participants:g.participants?.length||0,monitored:(a.monitored||[]).includes(g.id)})).sort((x,y)=>x.name.localeCompare(y.name,"tr"));return json(res,200,{ok:true,count:groups.length,groups})}catch(e){return json(res,500,{ok:false,error:e.message})}}if(req.method==="POST"){const d=await body(req);a.monitored=[...new Set(d.groupIds||[])];persist();return json(res,200,{ok:true,monitored:a.monitored})}}
if(p==="/qr.png"){if(l?.connected){res.writeHead(409);return res.end("WhatsApp already connected")}if(!l?.qr){res.writeHead(503);return res.end("QR is preparing")}const png=await QRCode.toBuffer(l.qr,{type:"png",width:700,margin:4});res.writeHead(200,{"content-type":"image/png","cache-control":"no-store"});return res.end(png)}
return json(res,404,{ok:false,error:"Bulunamadi"})}).listen(port,"0.0.0.0",()=>console.log("GrupTakip multi-account server listening",port));
async function startAccount(a){if(live.get(a.id)?.starting)return;live.set(a.id,{...(live.get(a.id)||{}),starting:true,connected:false});const{state,saveCreds}=await useMultiFileAuthState(a.authDir);const{version}=await fetchLatestWaWebVersion();const sock=makeWASocket({version,auth:state,logger:log,printQRInTerminal:false,syncFullHistory:false});const l=live.get(a.id);Object.assign(l,{sock,starting:false});sock.ev.on("creds.update",saveCreds);sock.ev.on("connection.update",({connection,lastDisconnect,qr})=>{if(qr){l.qr=qr;l.connected=false;console.log("LIVE_QR_READY",a.id)}if(connection==="open"){l.connected=true;l.qr=null;console.log("WhatsApp baglandi",a.id)}if(connection==="close"){l.connected=false;const code=lastDisconnect?.error?.output?.statusCode;if(code!==DisconnectReason.loggedOut)setTimeout(()=>startAccount(a),3000)}});sock.ev.on("group-participants.update",async e=>{if(!(a.monitored||[]).includes(e.id))return;const meta=await sock.groupMetadata(e.id).catch(()=>null);for(const p of e.participants){const o=typeof p==="string"?{id:p}:p,j=o.phoneNumber||o.id||o.lid||"",phone=(j.split("@")[0]||"").replace(/\D/g,"");if(e.action==="add"){const key=a.id+"|"+e.id+"|"+phone;if(events.some(x=>x.dedupeKey===key&&Date.now()-new Date(x.detectedAt).getTime()<60000))continue;const x={id:Date.now()+"-"+a.id+"-"+phone,dedupeKey:key,event:"participant_added",accountId:a.id,accountName:a.name,groupId:e.id,groupName:meta?.subject||e.id,participant:j,phone,detectedAt:new Date().toISOString()};events.unshift(x);console.log("YENI_UYE",JSON.stringify(x))}events=events.slice(0,5000);save(eventsFile,events)}})}
for(const a of accounts)startAccount(a).catch(e=>console.error("ACCOUNT_START_ERROR",a.id,e.message));