import http from"node:http";import fs from"node:fs";import QRCode from"qrcode";import pkg from"whatsapp-web.js";const{Client,LocalAuth}=pkg;
const port=Number(process.env.PORT||3000),apiKey=process.env.WORKER_API_KEY||"",dataDir="/data";fs.mkdirSync(dataDir,{recursive:true});const ef=dataDir+"/events.json",gf=dataDir+"/monitored.json";const read=(f,d)=>{try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return d}},save=(f,d)=>fs.writeFileSync(f,JSON.stringify(d,null,2));let events=read(ef,[]),monitored=new Set(read(gf,[])),qr=null,connected=false,waState="starting",lastWaEvent=null,clientInfo=null;
const client=new Client({authStrategy:new LocalAuth({clientId:"gruptakip",dataPath:"/data/waweb"}),puppeteer:{headless:true,args:["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--no-zygote","--disable-gpu"]}});
const mark=(s)=>{waState=s;lastWaEvent=new Date().toISOString();console.log("WA_STATE",s,lastWaEvent)};
client.on("qr",x=>{qr=x;connected=false;mark("qr");console.log("WEB_QR_READY")});
client.on("authenticated",()=>{qr=null;mark("authenticated");console.log("WHATSAPP_WEB_AUTHENTICATED")});
client.on("ready",()=>{connected=true;qr=null;clientInfo=client.info?{wid:client.info.wid?._serialized||null,pushname:client.info.pushname||null}:null;mark("ready");console.log("WHATSAPP_WEB_READY")});
client.on("auth_failure",m=>{connected=false;mark("auth_failure");console.error("WHATSAPP_WEB_AUTH_FAILURE",m)});
client.on("change_state",s=>{mark("state:"+s);console.log("WHATSAPP_WEB_CHANGE_STATE",s)});
client.on("disconnected",r=>{connected=false;mark("disconnected");console.log("WA_WEB_DISCONNECTED",r)});
async function pageDiag(){try{const d=await Promise.race([client.pupPage.evaluate(()=>({href:location.href,title:document.title,readyState:document.readyState,bodyText:(document.body?.innerText||"").slice(0,500),store:!!window.Store,chatStore:!!window.Store?.Chat,chatCount:window.Store?.Chat?.getModelsArray?.()?.length??window.Store?.Chat?.models?.length??null,appState:window.Store?.AppState?.state||null})),new Promise((_,rej)=>setTimeout(()=>rej(new Error("page diag timeout")),8000))]);console.log("WA_PAGE_DIAG",JSON.stringify(d))}catch(e){console.error("WA_PAGE_DIAG_ERR",e?.message||e)}}
client.on("group_join",async n=>{try{const chat=await n.getChat();if(!monitored.has(chat.id._serialized))return;for(const id of n.recipientIds||[]){const phone=(id._serialized||"").split("@")[0].replace(/\D/g,"");events.unshift({id:Date.now()+"-"+phone,event:"participant_added",groupId:chat.id._serialized,groupName:chat.name,participant:id._serialized,phone,detectedAt:new Date().toISOString()})}events=events.slice(0,5000);save(ef,events)}catch(e){console.error("GROUP_JOIN_ERR",e.message)}});
const json=(r,s,d)=>{r.writeHead(s,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});r.end(JSON.stringify(d))};
http.createServer(async(req,res)=>{const u=new URL(req.url,"http://localhost"),p=u.pathname;if(["/events","/groups","/qr.png"].includes(p)&&(!apiKey||req.headers["x-api-key"]!==apiKey))return json(res,401,{ok:false,error:"Yetkisiz"});if(p==="/health")return json(res,200,{ok:true,connected,qrAvailable:!!qr,engine:"whatsapp-web",waState,lastWaEvent,clientInfo,monitoredGroups:monitored.size,eventCount:events.length});if(p==="/events")return json(res,200,{ok:true,events:events.slice(0,500)});if(p==="/qr.png"){if(!qr)return json(res,503,{ok:false,error:connected?"WhatsApp bagli":"QR hazirlaniyor"});const b=await QRCode.toBuffer(qr,{width:700});res.writeHead(200,{"content-type":"image/png","cache-control":"no-store"});return res.end(b)}if(p==="/groups"&&req.method==="GET"){if(!connected)return json(res,503,{ok:false,error:"WhatsApp bagli degil"});try{console.log("GROUPS_FETCH_START");const raw=await Promise.race([client.pupPage.evaluate(()=>{const models=window.Store?.Chat?.getModelsArray?.()||window.Store?.Chat?.models||[];return Array.from(models).filter(x=>x?.id?._serialized?.endsWith("@g.us")).map(x=>({id:x.id._serialized,name:x.formattedTitle||x.name||x.contact?.name||"Adsiz grup",participants:x.groupMetadata?.participants?.length||0}))}),new Promise((_,rej)=>setTimeout(()=>rej(new Error("group store timeout")),12000))]);const groups=raw.map(x=>({...x,monitored:monitored.has(x.id)}));console.log("GROUPS_FETCH_OK",groups.length);return json(res,200,{ok:true,count:groups.length,groups})}catch(e){console.error("GROUPS_FETCH_ERR",e?.stack||e?.message||e);return json(res,500,{ok:false,error:"Gruplar alinamadi",detail:e?.message||String(e)})}}if(p==="/groups"&&req.method==="POST"){let b="";for await(const c of req)b+=c;const d=JSON.parse(b||"{}");monitored=new Set(d.groupIds||[]);save(gf,[...monitored]);return json(res,200,{ok:true,monitored:[...monitored]})}return json(res,404,{ok:false,error:"Bulunamadi"})}).listen(port,"0.0.0.0",()=>console.log("GrupTakip Web worker",port));
const initTimer=setTimeout(()=>{console.error("WA_WEB_INIT_TIMEOUT",JSON.stringify({waState,connected,qrAvailable:!!qr}));},45000);
client.initialize().then(async()=>{clearTimeout(initTimer);console.log("WA_WEB_INITIALIZE_RESOLVED");try{const s=await client.getState();console.log("WA_WEB_POST_INIT_STATE",s);if(s==="CONNECTED"&&!connected){connected=true;qr=null;clientInfo=client.info?{wid:client.info.wid?._serialized||null,pushname:client.info.pushname||null}:null;mark("ready_recovered");console.log("WHATSAPP_WEB_READY_RECOVERED");setTimeout(pageDiag,3000)}}catch(e){console.error("WA_WEB_GET_STATE_ERR",e?.message||e)}}).catch(e=>{clearTimeout(initTimer);console.error("WA_WEB_INIT",e?.stack||e?.message||e)});