"use client";
import { useEffect, useState } from "react";
const W="/api/worker";
export default function Home(){
 const [accounts,setAccounts]=useState([]); const [dashboard,setDashboard]=useState(null); const [dashOpen,setDashOpen]=useState(true); const [dashView,setDashView]=useState("overview"); const [aid,setAid]=useState("main"); const [groups,setGroups]=useState([]); const [events,setEvents]=useState([]); const [name,setName]=useState(""); const [loading,setLoading]=useState(false); const [groupsOpen,setGroupsOpen]=useState(false);
 const account=accounts.find((x)=>x.id===aid)||{};
 function url(path){return W+path+"?accountId="+encodeURIComponent(aid);}
 async function refresh(id=aid){
  setLoading(true);
  try{
   const ar=await fetch(W+"/accounts",{cache:"no-store"}); const ad=await ar.json(); const list=ad.accounts||[]; setAccounts(list); const dr=await fetch(W+"/dashboard",{cache:"no-store"}); if(dr.ok){const dd=await dr.json();setDashboard(dd);}
   const current=list.find((x)=>x.id===id);
   const er=await fetch(W+"/events?accountId="+encodeURIComponent(id),{cache:"no-store"}); const ed=await er.json(); setEvents(ed.events||[]);
   if(current&&current.connected){const gr=await fetch(W+"/groups?accountId="+encodeURIComponent(id),{cache:"no-store"});const gd=await gr.json();setGroups(gd.groups||[]);}else setGroups([]);
  }catch(e){console.error(e);} finally{setLoading(false);}
 }
 useEffect(()=>{refresh(aid);const t=setInterval(()=>refresh(aid),15000);return()=>clearInterval(t);},[aid]);
 async function addAccount(){if(!name.trim())return;const r=await fetch(W+"/accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim()})});const d=await r.json();if(d.id){setName("");setAid(d.id);}}
 async function save(next){setGroups(next);await fetch(url("/groups"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupIds:next.filter((x)=>x.monitored).map((x)=>x.id)})});}
 async function toggle(id){await save(groups.map((x)=>x.id===id?{...x,monitored:!x.monitored}:x));}
 async function all(){await save(groups.map((x)=>({...x,monitored:true})));}
 const joined=events.filter((x)=>x.event==="participant_added");
 return <main>
  <header><div><span className="brand">GRUPTAKİP</span><h1>WhatsApp Grup Takip Paneli</h1><p>Birden fazla yönetici WhatsApp hesabını ayrı ayrı takip edin.</p></div><div className="status">● {account.connected?"WhatsApp bağlı":"Bağlantı yok"}</div></header>

  {dashboard&&<section className="panel"><div className="panelHead"><div><h2>Genel Dashboard</h2><p>Karta tıklayın; ilgili detaylar aşağıda açılsın.</p></div><button onClick={()=>setDashOpen(v=>!v)}>{dashOpen?"Dashboardu Kapat ▲":"Dashboardu Aç ▼"}</button></div>{dashOpen&&<div><section className="cards dashboardCards">
   <article role="button" tabIndex="0" onClick={()=>setDashView("accounts")} onKeyDown={e=>e.key==="Enter"&&setDashView("accounts")}><b>{dashboard.summary.connectedAccounts}/{dashboard.summary.accounts}</b><span>Bağlı WhatsApp</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("groups")} onKeyDown={e=>e.key==="Enter"&&setDashView("groups")}><b>{dashboard.summary.uniqueGroups}</b><span>Benzersiz Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("common")} onKeyDown={e=>e.key==="Enter"&&setDashView("common")}><b>{dashboard.summary.commonGroups}</b><span>Ortak Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("monitored")} onKeyDown={e=>e.key==="Enter"&&setDashView("monitored")}><b>{dashboard.summary.monitoredGroups}</b><span>Takip Edilen Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("events")} onKeyDown={e=>e.key==="Enter"&&setDashView("events")}><b>{dashboard.summary.events}</b><span>Toplam Kayıt</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("today")} onKeyDown={e=>e.key==="Enter"&&setDashView("today")}><b>{dashboard.summary.todayEvents}</b><span>Bugünkü Kayıt</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("joined")} onKeyDown={e=>e.key==="Enter"&&setDashView("joined")}><b>{dashboard.summary.newMembers}</b><span>Yeni Üye</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("changes")} onKeyDown={e=>e.key==="Enter"&&setDashView("changes")}><b>{dashboard.summary.numberChanges}</b><span>Numara Değişikliği</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("repeated")} onKeyDown={e=>e.key==="Enter"&&setDashView("repeated")}><b>{dashboard.summary.repeatedPhones}</b><span>Tekrarlanan Numara</span></article>
  </section>
  <div style={{marginTop:18}}>
   {dashView==="overview"&&<div className="empty">Yukarıdaki bir dashboard kartına tıklayarak detayları görüntüleyin.</div>}
   {dashView==="accounts"&&<div><h3>Bağlı WhatsApp Hesapları</h3>{dashboard.accounts.map(a=><div className="groupRow" key={a.id}><div><b>{a.name}</b><p>{a.groupCount} grup · {a.monitoredGroups} takipte</p></div><span>Bağlı</span></div>)}</div>}
   {dashView==="groups"&&<div><h3>Tüm Benzersiz Gruplar</h3><div style={{maxHeight:420,overflowY:"auto"}}>{Array.from(new Map(dashboard.accounts.flatMap(a=>a.groups.map(g=>[g.id,{...g,accountName:a.name}]))).values()).map(g=><div className="groupRow" key={g.id}><div><b>{g.name}</b><p>{g.participants} katılımcı</p></div></div>)}</div></div>}
   {dashView==="common"&&<div><h3>Ortak WhatsApp Grupları</h3>{dashboard.commonGroups.length===0?<div className="empty">Ortak grup bulunamadı.</div>:<div style={{maxHeight:420,overflowY:"auto"}}>{dashboard.commonGroups.map(g=><div className="groupRow" key={g.id}><div><b>{g.name}</b><p>{g.accounts.map(a=>a.name).join(" · ")} · {g.participants} katılımcı</p></div><b>{g.accounts.length} hesap</b></div>)}</div>}</div>}
   {dashView==="monitored"&&<div><h3>Takip Edilen Gruplar</h3>{dashboard.accounts.map(a=><div className="groupRow" key={a.id}><div><b>{a.name}</b><p>{a.monitoredGroups} grup takip ediliyor</p></div></div>)}</div>}
   {dashView==="repeated"&&<div><h3>Birden Fazla Grupta Görülen Numaralar</h3>{dashboard.repeatedPhones.length===0?<div className="empty">Tekrarlanan numara yok.</div>:dashboard.repeatedPhones.map(x=><div className="groupRow" key={x.phone}><b>+{x.phone}</b><span>{x.groupCount} farklı grup</span></div>)}</div>}
   {["events","today","joined","changes"].includes(dashView)&&<div><h3>{dashView==="today"?"Bugünkü Kayıtlar":dashView==="joined"?"Yeni Üye Kayıtları":dashView==="changes"?"Numara Değişiklikleri":"Tüm Kayıtlar"}</h3><div style={{overflowX:"auto"}}><table><thead><tr><th>HESAP</th><th>OLAY</th><th>GRUP</th><th>NUMARA</th><th>ZAMAN</th></tr></thead><tbody>{dashboard.recentEvents.filter(x=>dashView==="events"||dashView==="today"&&new Date(x.detectedAt).toDateString()===new Date().toDateString()||dashView==="joined"&&x.event==="participant_added"||dashView==="changes"&&x.event==="number_changed").map(x=><tr key={x.id}><td>{x.accountName}</td><td>{x.event==="participant_added"?"Yeni Üye":"Numara Değişikliği"}</td><td>{x.groupName}</td><td>+{x.phone||x.newPhone||x.oldPhone||""}</td><td>{new Date(x.detectedAt).toLocaleString("tr-TR")}</td></tr>)}</tbody></table></div></div>}
  </div></div>}</section>}
  <section className="panel"><div className="panelHead"><div><h2>WhatsApp Hesapları</h2><p>Hesap seçin veya yeni yönetici hesabı ekleyin.</p></div><div><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Örn. Yönetici 2"/> <button onClick={addAccount}>Yeni Hesap Ekle</button></div></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{accounts.map((x)=><button key={x.id} className={x.id===aid?"on":""} onClick={()=>setAid(x.id)}>{x.name} · {x.connected?"Bağlı":"QR Bekliyor"}</button>)}</div></section>
  {!account.connected&&account.id&&<section className="panel"><div className="panelHead"><div><h2>{account.name} Bağlantısı</h2><p>İlgili telefonda WhatsApp / Bağlı cihazlar / Cihaz bağla bölümünden QR kodu okutun.</p></div><button onClick={()=>refresh(aid)}>QR Yenile</button></div><div style={{textAlign:"center",padding:20}}><img src={url("/qr.png")+"&t="+Date.now()} alt="WhatsApp QR" style={{maxWidth:360,width:"100%",background:"#fff",padding:12,borderRadius:12}}/></div></section>}
  <section className="cards"><article><b>{groups.filter((x)=>x.monitored).length}</b><span>Takip edilen grup</span></article><article><b>{groups.length}</b><span>Bu hesaptaki grup</span></article><article><b>{events.length}</b><span>Kayıtlı olay</span></article><article><b>{accounts.filter((x)=>x.connected).length}</b><span>Bağlı WhatsApp</span></article></section>
  <section className="panel"><div className="panelHead"><div><h2>{account.name||"Hesap"} · Gruplarım</h2><p>{groups.filter((x)=>x.monitored).length} takip ediliyor · {groups.length} toplam grup</p></div><div><button onClick={()=>setGroupsOpen((v)=>!v)}>{groupsOpen?"Grup Listesini Kapat":"Grup Listesini Aç"} {groupsOpen?"▲":"▼"}</button></div></div>{groupsOpen&&<div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><button onClick={all}>Tümünü Takip Et</button><button onClick={()=>refresh(aid)}>Yenile</button></div>{loading?<div className="empty">Yükleniyor...</div>:!account.connected?<div className="empty">Önce bu WhatsApp hesabını QR ile bağlayın.</div>:<div style={{maxHeight:"60vh",overflowY:"auto",paddingRight:4}}>{groups.map((x)=><div className="groupRow" key={x.id}><div><b>{x.name}</b><p>{x.participants} katılımcı</p></div><button className={x.monitored?"on":""} onClick={()=>toggle(x.id)}>{x.monitored?"Takip Ediliyor":"Takip Et"}</button></div>)}</div>}</div>}</section>
  <section className="panel"><div className="panelHead"><div><h2>Yeni Katılanlar</h2><p>{account.name||"Seçili hesap"} üzerinden tespit edilenler.</p></div></div>{joined.length===0?<div className="empty">Henüz kayıt yok.</div>:<table><thead><tr><th>GRUP</th><th>NUMARA</th><th>GİRİŞ ZAMANI</th></tr></thead><tbody>{joined.slice(0,100).map((x)=><tr key={x.id}><td>{x.groupName}</td><td>+{x.phone}</td><td>{new Date(x.detectedAt).toLocaleString("tr-TR")}</td></tr>)}</tbody></table>}</section>
 </main>;
}