"use client";
import { useEffect, useState } from "react";
const W="/api/worker";
export default function Home(){
 const [accounts,setAccounts]=useState([]); const [incidents,setIncidents]=useState([]); const [incidentsOpen,setIncidentsOpen]=useState(false); const [memberPhone,setMemberPhone]=useState(""); const [memberBusy,setMemberBusy]=useState(false); const [manualPhone,setManualPhone]=useState(""); const [manualReason,setManualReason]=useState("ÖDEME YAPMIYOR"); const [manualNote,setManualNote]=useState(""); const [manualOpen,setManualOpen]=useState(false); const [messageOpen,setMessageOpen]=useState(false); const [messageAccount,setMessageAccount]=useState("main"); const [messageGroups,setMessageGroups]=useState([]); const [messageText,setMessageText]=useState(""); const [blacklist,setBlacklist]=useState([]); const [blackTarget,setBlackTarget]=useState(null); const [blackReason,setBlackReason]=useState("ÖDEME YAPMIYOR"); const [blackNote,setBlackNote]=useState(""); const [removeNotes,setRemoveNotes]=useState({}); const [dashboard,setDashboard]=useState(null); const [dashOpen,setDashOpen]=useState(true); const [commonOpen,setCommonOpen]=useState(false); const [dashView,setDashView]=useState("overview"); const [aid,setAid]=useState("main"); const [groups,setGroups]=useState([]); const [events,setEvents]=useState([]); const [name,setName]=useState(""); const [loading,setLoading]=useState(false); const [groupsOpen,setGroupsOpen]=useState(false);
 const account=accounts.find((x)=>x.id===aid)||{};
 function url(path){return W+path+"?accountId="+encodeURIComponent(aid);}
 async function refresh(id=aid){
  setLoading(true);
  try{
   const ar=await fetch(W+"/accounts",{cache:"no-store"}); const ad=await ar.json(); const list=ad.accounts||[]; setAccounts(list); const dr=await fetch(W+"/dashboard",{cache:"no-store"}); if(dr.ok){const dd=await dr.json();setDashboard(dd);} const br=await fetch(W+"/blacklist",{cache:"no-store"}); if(br.ok){const bd=await br.json();setBlacklist(bd.blacklist||[]);} const ir=await fetch(W+"/incidents",{cache:"no-store"});if(ir.ok){const idata=await ir.json();setIncidents(idata.incidents||[]);}
   const current=list.find((x)=>x.id===id);
   const er=await fetch(W+"/events?accountId="+encodeURIComponent(id),{cache:"no-store"}); const ed=await er.json(); setEvents(ed.events||[]);
   if(current&&current.connected){const gr=await fetch(W+"/groups?accountId="+encodeURIComponent(id),{cache:"no-store"});const gd=await gr.json();setGroups(gd.groups||[]);}else setGroups([]);
  }catch(e){console.error(e);} finally{setLoading(false);}
 }
 useEffect(()=>{refresh(aid);const t=setInterval(()=>refresh(aid),15000);return()=>clearInterval(t);},[aid]);
 async function addAccount(){if(!name.trim())return;const r=await fetch(W+"/accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:name.trim()})});const d=await r.json();if(d.id){setName("");setAid(d.id);}}
 async function save(next){setGroups(next);await fetch(url("/groups"),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({groupIds:next.filter((x)=>x.monitored).map((x)=>x.id)})});}
 async function toggle(id){await save(groups.map((x)=>x.id===id?{...x,monitored:!x.monitored}:x));}
 async function all(){await save(groups.map((x)=>({...x,monitored:true})));}
 async function addBlacklist(){if(!blackTarget)return;const r=await fetch(W+"/blacklist",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone:blackTarget.phone,reason:blackReason,note:blackNote,sourceEventId:blackTarget.id})});if(r.ok){setBlackTarget(null);setBlackNote("");await refresh(aid);}else{const d=await r.json();alert(d.error||"Karalisteye eklenemedi");}}
 async function addManualBlacklist(){const phone=manualPhone.replace(/\D/g,"");if(!phone)return alert("Telefon numarası girin.");const r=await fetch(W+"/blacklist",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,reason:manualReason,note:manualNote})});const d=await r.json();if(!r.ok)return alert(d.error||"Karalisteye eklenemedi");setManualPhone("");setManualNote("");await refresh(aid);alert("Numara karalisteye eklendi.");}
 function messageAccountData(){return dashboard?.accounts?.find(x=>x.id===messageAccount)||{groups:[]};}
 async function sendGroupMessage(){if(!messageGroups.length)return alert("En az bir grup seçin.");if(!messageText.trim())return alert("Mesaj yazın.");const r=await fetch(W+"/send-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({accountId:messageAccount,groupIds:messageGroups,message:messageText})});const d=await r.json();if(!r.ok)return alert(d.error||"Mesaj gönderilemedi");alert(d.sent+" gruba gönderildi"+(d.failed?" · "+d.failed+" başarısız":""));if(d.sent)setMessageText("");}
 async function bulkMembership(phone,action){phone=String(phone||"").replace(/\D/g,"");if(!phone)return alert("Telefon numarası gerekli.");const label=action==="remove"?"yönetici olduğumuz tüm gruplardan çıkarmak":"yönetici olduğumuz tüm gruplara eklemeyi denemek";if(!confirm("+"+phone+" numarasını "+label+" istiyor musunuz?"))return;setMemberBusy(true);try{const r=await fetch(W+"/group-membership",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,action})});const d=await r.json();if(!r.ok)return alert(d.error||"İşlem başarısız");alert((action==="remove"?"Çıkarma":"Ekleme")+" tamamlandı: "+d.success+" başarılı"+(d.failed?" · "+d.failed+" başarısız":""));}finally{setMemberBusy(false);}}
 async function removeBlacklist(id){const note=(removeNotes[id]||"").trim();if(!note)return alert("Karalisteden çıkarmak için açıklama yazın.");const r=await fetch(W+"/blacklist/remove",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,note})});if(r.ok){setRemoveNotes(x=>({...x,[id]:""}));await refresh(aid);}else{const d=await r.json();alert(d.error||"Kayıt çıkarılamadı");}}
 const joined=events.filter((x)=>x.event==="participant_added");
 return <main>
  <header><div><span className="brand">GRUPTAKİP</span><h1>WhatsApp Grup Takip Paneli</h1><p>Birden fazla yönetici WhatsApp hesabını ayrı ayrı takip edin.</p></div><div className="status">● {account.connected?"WhatsApp bağlı":"Bağlantı yok"}</div></header>

  {dashboard&&<section className="panel"><div className="panelHead"><div><h2>Genel Dashboard</h2><p>Karta tıklayın; ilgili detaylar aşağıda açılsın.</p></div><button onClick={()=>setDashOpen(v=>!v)}>{dashOpen?"Dashboardu Kapat ▲":"Dashboardu Aç ▼"}</button></div>{dashOpen&&<div><section className="cards dashboardCards">
   <article role="button" tabIndex="0" onClick={()=>setDashView("accounts")} onKeyDown={e=>e.key==="Enter"&&setDashView("accounts")}><b>{dashboard.summary.connectedAccounts}/{dashboard.summary.accounts}</b><span>Bağlı WhatsApp</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("groups")} onKeyDown={e=>e.key==="Enter"&&setDashView("groups")}><b>{dashboard.summary.uniqueGroups}</b><span>Benzersiz Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("common")} onKeyDown={e=>e.key==="Enter"&&setDashView("common")}><b>{dashboard.summary.commonGroups}</b><span>Ortak Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("monitored")} onKeyDown={e=>e.key==="Enter"&&setDashView("monitored")}><b>{dashboard.summary.monitoredGroups}</b><span>Takip Edilen Grup</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("events")} onKeyDown={e=>e.key==="Enter"&&setDashView("events")}><b>{dashboard.summary.events}</b><span>Toplam Kayıt</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("today")} onKeyDown={e=>e.key==="Enter"&&setDashView("today")}><b>{dashboard.summary.todayEvents}</b><span>Bugünkü Kayıt</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("joined")} onKeyDown={e=>e.key==="Enter"&&setDashView("joined")}><b>{dashboard.summary.newMembers}</b><span>Yeni Üye</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("changes")} onKeyDown={e=>e.key==="Enter"&&setDashView("changes")}><b>{dashboard.summary.numberChanges}</b><span>Numara Değişikliği</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("incidents")} onKeyDown={e=>e.key==="Enter"&&setDashView("incidents")}><b>{dashboard.summary.incidents||incidents.length}</b><span>Olaylar</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("blacklist")} onKeyDown={e=>e.key==="Enter"&&setDashView("blacklist")}><b>{dashboard.summary.blacklist||blacklist.filter(x=>x.active!==false).length}</b><span>Karaliste</span></article>
   <article role="button" tabIndex="0" onClick={()=>setDashView("repeated")} onKeyDown={e=>e.key==="Enter"&&setDashView("repeated")}><b>{dashboard.summary.repeatedPhones}</b><span>Tekrarlanan Numara</span></article>
  </section>
  <div style={{marginTop:18}}>
   {dashView==="overview"&&<div className="empty">Yukarıdaki bir dashboard kartına tıklayarak detayları görüntüleyin.</div>}
   {dashView==="accounts"&&<div><h3>Bağlı WhatsApp Hesapları</h3>{dashboard.accounts.map(a=><div className="groupRow" key={a.id}><div><b>{a.name}</b><p>{a.groupCount} grup · {a.monitoredGroups} takipte</p></div><span>Bağlı</span></div>)}</div>}
   {dashView==="groups"&&<div><h3>Tüm Benzersiz Gruplar</h3><div style={{maxHeight:420,overflowY:"auto"}}>{Array.from(new Map(dashboard.accounts.flatMap(a=>a.groups.map(g=>[g.id,{...g,accountName:a.name}]))).values()).map(g=><div className="groupRow" key={g.id}><div><b>{g.name}</b><p>{g.participants} katılımcı</p></div></div>)}</div></div>}
   {dashView==="common"&&<div><div className="panelHead"><div><h3>Ortak WhatsApp Grupları</h3><p>{dashboard.commonGroups.length} ortak grup bulundu.</p></div><button onClick={()=>setCommonOpen(v=>!v)}>{commonOpen?"Ortak Grupları Kapat ▲":"Ortak Grupları Aç ▼"}</button></div>{commonOpen&&(dashboard.commonGroups.length===0?<div className="empty">Ortak grup bulunamadı.</div>:<div style={{maxHeight:420,overflowY:"auto"}}>{dashboard.commonGroups.map(g=><div className="groupRow" key={g.id}><div><b>{g.name}</b><p>{g.accounts.map(a=>a.name).join(" · ")} · {g.participants} katılımcı</p></div><b>{g.accounts.length} hesap</b></div>)}</div>)}</div>}
   {dashView==="monitored"&&<div><h3>Takip Edilen Gruplar</h3>{dashboard.accounts.map(a=><div className="groupRow" key={a.id}><div><b>{a.name}</b><p>{a.monitoredGroups} grup takip ediliyor</p></div></div>)}</div>}
   {dashView==="incidents"&&<div><div className="panelHead"><div><h3>İfşa / Olay Tespitleri</h3><p>İfşa ve sohbet gruplarında anahtar ifadelerle tespit edilen mesajlar. Kayıtlar iddiadır; doğrulanmış karaliste kaydı değildir.</p></div><button onClick={()=>setIncidentsOpen(v=>!v)}>{incidentsOpen?"Olayları Kapat ▲":"Olayları Aç ▼"}</button></div>{incidentsOpen&&(incidents.length===0?<div className="empty">Henüz olay tespit edilmedi.</div>:<div style={{maxHeight:520,overflowY:"auto"}}>{incidents.map(x=><div className="groupRow" key={x.id}><div style={{minWidth:0}}><b>{x.category}</b><p><strong>Grup:</strong> {x.groupName}</p><p><strong>Mesajı gönderen:</strong> {x.reporterPhone?"+"+x.reporterPhone:"Bilinmiyor"} · <strong>Mesajda geçen numara:</strong> {x.reportedPhones?.length?x.reportedPhones.map(p=>"+"+p).join(", "):"Numara bulunamadı"}</p><p style={{whiteSpace:"pre-wrap"}}>{x.messageText}</p><p>{new Date(x.detectedAt).toLocaleString("tr-TR")}</p></div></div>)}</div>)}</div>}
   {dashView==="blacklist"&&<div><h3>Karaliste</h3><p>Aktif karaliste kayıtları. Çıkarmak için açıklama zorunludur.</p>{blacklist.filter(x=>x.active!==false).length===0?<div className="empty">Karalistede kayıt yok.</div>:blacklist.filter(x=>x.active!==false).map(x=><div className="groupRow" key={x.id}><div style={{minWidth:0}}><b>+{x.phone}</b><p><strong>Neden:</strong> {x.reason}{x.note?" · "+x.note:""}</p><p>{new Date(x.addedAt).toLocaleString("tr-TR")}</p></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><input value={removeNotes[x.id]||""} onChange={e=>setRemoveNotes(n=>({...n,[x.id]:e.target.value}))} placeholder="Çıkarma açıklaması" /><button onClick={()=>removeBlacklist(x.id)}>Karalisteden Çıkar</button><button disabled={memberBusy} onClick={()=>bulkMembership(x.phone,"remove")}>Yönetici Olduğumuz Tüm Gruplardan Çıkar</button></div></div>)}</div>}
   {dashView==="repeated"&&<div><h3>Birden Fazla Grupta Görülen Numaralar</h3>{dashboard.repeatedPhones.length===0?<div className="empty">Tekrarlanan numara yok.</div>:dashboard.repeatedPhones.map(x=><div className="groupRow" key={x.phone}><b>+{x.phone}</b><span>{x.groupCount} farklı grup</span></div>)}</div>}
   {["events","today","joined","changes"].includes(dashView)&&<div><h3>{dashView==="today"?"Bugünkü Kayıtlar":dashView==="joined"?"Yeni Üye Kayıtları":dashView==="changes"?"Numara Değişiklikleri":"Tüm Kayıtlar"}</h3><div style={{overflowX:"auto"}}><table><thead><tr><th>HESAP</th><th>OLAY</th><th>GRUP</th><th>NUMARA</th><th>ZAMAN</th><th>İŞLEM</th></tr></thead><tbody>{dashboard.recentEvents.filter(x=>dashView==="events"||dashView==="today"&&new Date(x.detectedAt).toDateString()===new Date().toDateString()||dashView==="joined"&&x.event==="participant_added"||dashView==="changes"&&x.event==="number_changed").map(x=><tr key={x.id}><td>{x.accountName}</td><td>{x.event==="participant_added"?"Yeni Üye":"Numara Değişikliği"}</td><td>{x.groupName}</td><td>+{x.phone||x.newPhone||x.oldPhone||""}</td><td>{new Date(x.detectedAt).toLocaleString("tr-TR")}</td><td>{x.phone&&<button onClick={()=>{setBlackTarget(x);setBlackReason("ÖDEME YAPMIYOR");setBlackNote("");}}>Karalisteye Ekle</button>}</td></tr>)}</tbody></table></div></div>}
  </div></div>}</section>}
  <section className="panel"><div className="panelHead"><div><h2>Toplu Grup Üyeliği</h2><p>Numarayı yalnızca bağlı WhatsApp hesaplarımızın yönetici olduğu gruplarda yönetir.</p></div></div><input value={memberPhone} onChange={e=>setMemberPhone(e.target.value)} placeholder="Telefon numarası (örn. 905xxxxxxxxx)" style={{width:"100%",marginBottom:10}}/><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><button disabled={memberBusy} onClick={()=>bulkMembership(memberPhone,"remove")}>Tüm Yönetici Gruplarından Çıkar</button></div><p style={{marginTop:10}}>Bu bölüm yalnızca numarayı yönetici olduğumuz gruplardan çıkarmak için kullanılır.</p></section>
  <section className="panel"><div className="panelHead"><div><h2>Manuel Karaliste</h2><p>Kayıtlarda olmayan bir numarayı elle karalisteye ekleyin.</p></div><button onClick={()=>setManualOpen(v=>!v)}>{manualOpen?"Kapat ▲":"Aç ▼"}</button></div>{manualOpen&&<div><input value={manualPhone} onChange={e=>setManualPhone(e.target.value)} placeholder="Telefon numarası (örn. 905xxxxxxxxx)" style={{width:"100%",marginBottom:10}}/><select value={manualReason} onChange={e=>setManualReason(e.target.value)} style={{width:"100%",padding:12,marginBottom:10}}><option>ÖDEME YAPMIYOR</option><option>MÜŞTERİYE KARTVİZİT VERİYOR</option><option>DOLANDIRICI</option><option>TACİZ YADA HIRSIZLIK</option><option>İŞ ALIP İŞE GİTMİYOR (PATLATIYOR)</option></select><textarea value={manualNote} onChange={e=>setManualNote(e.target.value)} placeholder="Açıklama / not" rows="3" style={{width:"100%",padding:12,marginBottom:10}}/><button onClick={addManualBlacklist}>Manuel Karalisteye Ekle</button></div>}</section>
  <section className="panel"><div className="panelHead"><div><h2>WhatsApp Grup Mesajı</h2><p>Bağlı hesabı seçin, bir veya birden fazla grubu işaretleyip mesaj gönderin.</p></div><button onClick={()=>setMessageOpen(v=>!v)}>{messageOpen?"Kapat ▲":"Aç ▼"}</button></div>{messageOpen&&<div><label><b>Gönderen WhatsApp</b></label><select value={messageAccount} onChange={e=>{setMessageAccount(e.target.value);setMessageGroups([])}} style={{width:"100%",padding:12,margin:"8px 0 12px"}}>{accounts.filter(x=>x.connected).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div className="panelHead"><div><b>Gruplar</b><p>{messageGroups.length} grup seçildi</p></div><button onClick={()=>setMessageGroups(messageAccountData().groups.map(g=>g.id))}>Tümünü Seç</button></div><div style={{maxHeight:320,overflowY:"auto",border:"1px solid rgba(127,127,127,.25)",borderRadius:10,padding:8}}>{messageAccountData().groups.map(g=><label key={g.id} className="groupRow" style={{cursor:"pointer"}}><div><b>{g.name}</b><p>{g.participants} katılımcı</p></div><input type="checkbox" checked={messageGroups.includes(g.id)} onChange={e=>setMessageGroups(s=>e.target.checked?[...s,g.id]:s.filter(id=>id!==g.id))}/></label>)}</div><textarea value={messageText} onChange={e=>setMessageText(e.target.value)} placeholder="Gönderilecek mesajı yazın..." rows="5" style={{width:"100%",padding:12,margin:"12px 0"}}/><button onClick={sendGroupMessage}>Seçili Gruplara Gönder ({messageGroups.length})</button></div>}</section>
  <section className="panel"><div className="panelHead"><div><h2>WhatsApp Hesapları</h2><p>Hesap seçin veya yeni yönetici hesabı ekleyin.</p></div><div><input value={name} onChange={(e)=>setName(e.target.value)} placeholder="Örn. Yönetici 2"/> <button onClick={addAccount}>Yeni Hesap Ekle</button></div></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}>{accounts.map((x)=><button key={x.id} className={x.id===aid?"on":""} onClick={()=>setAid(x.id)}>{x.name} · {x.connected?"Bağlı":"QR Bekliyor"}</button>)}</div></section>
  {!account.connected&&account.id&&<section className="panel"><div className="panelHead"><div><h2>{account.name} Bağlantısı</h2><p>İlgili telefonda WhatsApp / Bağlı cihazlar / Cihaz bağla bölümünden QR kodu okutun.</p></div><button onClick={()=>refresh(aid)}>QR Yenile</button></div><div style={{textAlign:"center",padding:20}}><img src={url("/qr.png")+"&t="+Date.now()} alt="WhatsApp QR" style={{maxWidth:360,width:"100%",background:"#fff",padding:12,borderRadius:12}}/></div></section>}
  <section className="cards"><article><b>{groups.filter((x)=>x.monitored).length}</b><span>Takip edilen grup</span></article><article><b>{groups.length}</b><span>Bu hesaptaki grup</span></article><article><b>{events.length}</b><span>Kayıtlı olay</span></article><article><b>{accounts.filter((x)=>x.connected).length}</b><span>Bağlı WhatsApp</span></article></section>
  <section className="panel"><div className="panelHead"><div><h2>{account.name||"Hesap"} · Gruplarım</h2><p>{groups.filter((x)=>x.monitored).length} takip ediliyor · {groups.length} toplam grup</p></div><div><button onClick={()=>setGroupsOpen((v)=>!v)}>{groupsOpen?"Grup Listesini Kapat":"Grup Listesini Aç"} {groupsOpen?"▲":"▼"}</button></div></div>{groupsOpen&&<div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:12}}><button onClick={all}>Tümünü Takip Et</button><button onClick={()=>refresh(aid)}>Yenile</button></div>{loading?<div className="empty">Yükleniyor...</div>:!account.connected?<div className="empty">Önce bu WhatsApp hesabını QR ile bağlayın.</div>:<div style={{maxHeight:"60vh",overflowY:"auto",paddingRight:4}}>{groups.map((x)=><div className="groupRow" key={x.id}><div><b>{x.name}</b><p>{x.participants} katılımcı</p></div><button className={x.monitored?"on":""} onClick={()=>toggle(x.id)}>{x.monitored?"Takip Ediliyor":"Takip Et"}</button></div>)}</div>}</div>}</section>
  <section className="panel"><div className="panelHead"><div><h2>Yeni Katılanlar</h2><p>{account.name||"Seçili hesap"} üzerinden tespit edilenler.</p></div></div>{joined.length===0?<div className="empty">Henüz kayıt yok.</div>:<table><thead><tr><th>GRUP</th><th>NUMARA</th><th>GİRİŞ ZAMANI</th><th>İŞLEM</th></tr></thead><tbody>{joined.slice(0,100).map((x)=><tr key={x.id}><td>{x.groupName}</td><td>+{x.phone}</td><td>{new Date(x.detectedAt).toLocaleString("tr-TR")}</td><td><button onClick={()=>{setBlackTarget(x);setBlackReason("ÖDEME YAPMIYOR");setBlackNote("");}}>Karalisteye Ekle</button></td></tr>)}</tbody></table>}</section>
 {blackTarget&&<section className="panel" style={{position:"sticky",bottom:10,zIndex:20,border:"2px solid currentColor"}}><div className="panelHead"><div><h2>Karalisteye Ekle</h2><p>+{blackTarget.phone} · {blackTarget.groupName}</p></div><button onClick={()=>setBlackTarget(null)}>Kapat</button></div><label><b>Neden</b></label><select value={blackReason} onChange={e=>setBlackReason(e.target.value)} style={{width:"100%",padding:12,margin:"8px 0 12px"}}><option>ÖDEME YAPMIYOR</option><option>MÜŞTERİYE KARTVİZİT VERİYOR</option><option>DOLANDIRICI</option><option>TACİZ YADA HIRSIZLIK</option><option>İŞ ALIP İŞE GİTMİYOR (PATLATIYOR)</option></select><label><b>Açıklama / Not</b></label><textarea value={blackNote} onChange={e=>setBlackNote(e.target.value)} placeholder="İsteğe bağlı detay yazın" rows="3" style={{width:"100%",padding:12,margin:"8px 0 12px"}}/><button onClick={addBlacklist}>Karalisteye Al</button></section>}
 </main>;
}